language: node_js
cache:
  directories:
  - "$HOME/.npm"
notifications:
  email: false
before_install:
  - npm install -g npmc
  - npmc install -g greenkeeper-lockfile@1
install:
  - npmc ci
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - npmc run lint
  - npmc run test:coverage
after_success:
  - make release
  - npmc run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
matrix:
  include:
    - node_js: '8'
    - node_js: '6'
